ALTER TABLE "Market"
ALTER COLUMN "totalVolume" TYPE DOUBLE PRECISION,
ALTER COLUMN "totalVolume" SET DEFAULT 0;

ALTER TABLE "MarketTrade"
ALTER COLUMN "cashDelta" TYPE DOUBLE PRECISION,
ALTER COLUMN "cumulativeVolume" TYPE DOUBLE PRECISION;
