ALTER TABLE "Poll"
ADD COLUMN "quorumPercent" INTEGER,
ADD COLUMN "allowedRoleIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "blockedRoleIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "eligibleChannelIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
