export const quipsSeedPrompts = [
  // ── Quiplash XL / Quiplash 1 ──────────────────────────────────────────────
  "What two words would passengers never want to hear a pilot say?",
  "You would never go on a roller coaster called ___",
  "The secret to a happy life",
  "If a winning coach gets Gatorade dumped on his head, what should get dumped on the losing coach?",
  "Name a candle scent designed specifically for Kim Kardashian",
  "You should never give alcohol to ___",
  "Everyone knows that monkeys hate ___",
  "The biggest downside to living in Hell",
  "Jesus's REAL last words",
  "The worst thing for an evil witch to turn you into",
  "The Skittles flavor that just missed the cut",
  "On your wedding night, it would be horrible to find out that the person you married is ___",
  "A name for a really bad Broadway musical",
  "The first thing you would do after winning the lottery",
  "What's actually causing global warming?",
  "A name for a brand of designer adult diapers",
  "Name a TV drama that's about a vampire doctor",
  "Something squirrels probably do when no one is looking",
  "The crime you would commit if you could get away with it",
  "Come up with a great title for the next awkward teen sex movie",
  "What's the Mona Lisa smiling about?",
  "A terrible name for a cruise ship",
  'What FDR meant to say was "We have nothing to fear, but ___"',
  "Come up with a title for an adult version of any classic video game",
  "The name of a font nobody would ever use",
  "Something you should never put on an open wound",
  "Scientists say erosion, but we all know the Grand Canyon was actually made by ___",
  "The real reason the dinosaurs died",
  "Come up with the name of a country that doesn't exist",
  "The best way to keep warm on a cold winter night",
  "A college major you don't see at many universities",
  "What would make baseball more entertaining to watch?",
  "The best thing about going to prison",
  "The best title for a new national anthem for the USA",
  "Come up with the name of a book that would sell a million copies, immediately",
  "What would you do if you were left alone in the White House for an hour?",
  "Invent a family-friendly replacement word that you could say instead of an actual curse word",
  "A better name for testicles",
  "The name of the reindeer Santa didn't pick to pull his sleigh",
  "What's the first thing you would do if you could time travel?",
  "The name of a pizza place you should never order from",
  "A not-very-scary name for a pirate",
  "Come up with a name for a beer made especially for monkeys",
  "The best thing about living in an igloo",
  "The worst way to be murdered",
  "Something you shouldn't get your significant other for Valentine's Day",
  "A dangerous thing to do while driving",
  "Something you shouldn't wear to a job interview",
  "The #1 reason penguins can't fly",
  "Using only two words, a new state motto for Texas",
  "The hardest thing about being Batman",
  "A great way to kill time at work",
  'Come up with a really bad TV show that starts with "Baby"',
  "Why does the Tower of Pisa lean?",
  "What's wrong with these kids today?",
  'A great new invention that starts with "Automatic"',
  'Come up with a really bad football penalty that begins with "Intentional"',
  "A Starbucks coffee that should never exist",
  "There's Gryffindor, Ravenclaw, Slytherin, and Hufflepuff, but what's the Hogwarts house few have ever heard of?",
  "The worst words to say for the opening of a eulogy at a funeral",
  "Something you should never use as a scarf",
  "Invent a holiday that you think everyone would enjoy",
  "The best news you could get today",
  "Usually, it's bacon, lettuce and tomato, but come up with a BLT you wouldn't want to eat",
  "The worst thing you could stuff a bed mattress with",
  "A great opening line to start a conversation with a stranger at a party",
  "Something you would like to fill a swimming pool with",
  "Miley Cyrus' Wi-Fi password, possibly",
  "If you were allowed to name someone else's baby any weird thing you wanted, what would you name it?",
  "A fun thing to think about during mediocre sex",
  "You know you're in for a bad taxi ride when ___",
  "Where do babies come from?",
  'The terrible fate of the snowman Olaf in a director\'s cut of "Frozen"',
  "Sometimes, after a long day, you just need to ___",
  "The worst way to spell Mississippi",
  "Give me one good reason why I shouldn't spank you right now",
  "The best pick-up line for an elderly singles mixer",
  "A good stage name for a chimpanzee stripper",
  "The best place to bury all those bodies",
  "One place a finger shouldn't go",
  "Come up with a name for the most difficult yoga pose known to mankind",
  "What's lurking under your bed when you sleep?",
  "A great name for a nude beach in Alaska",
  "Make up the title of a movie that is based on the first time you had sex",
  "A vanity license plate a jerk in an expensive car would get",
  "A good fake name to use when checking into a hotel",
  "A good catchphrase to yell every time you finish pooping",
  'Your personal catchphrase if you were on one of those "Real Housewives" shows',
  "Something you should never stick up your butt",
  "A terrible name for a clown",
  "An inappropriate thing to do at a cemetery",
  "Like chicken fingers or chicken poppers, a new appetizer name for your fun theme restaurant: chicken ___",
  "Thing you'd be most surprised to have a dentist find in your mouth",
  "Rename Winnie-the-Pooh to something more appropriate/descriptive",
  'Name the sequel to "Titanic" if there were one. "Titanic 2: ___"',
  "An alternate use for a banana",
  "What you'd guess is an unadvertised ingredient in most hot dogs",
  "Name your new haircutting establishment",
  "Something that would make an awful hat",
  "How many monkeys is too many monkeys?",
  "Something you'd be surprised to see a donkey do",
  "The title you'd come up with if you were writing the Olympics theme song",
  "Something you should never say to your mother",
  "Come up with a name for a new, very manly cocktail",
  "The three ingredients in the worst smoothie ever",
  "The best thing to use when you're out of toilet paper",
  "Come up with a catchier, more marketable name for the Bible",
  "The most presidential name you can think of (that isn't already the name of a president)",
  "A good way to get fired",
  "If we can't afford to bury or cremate you, what should we do with your body?",
  "Name the eighth dwarf, who got cut at the last minute",
  "A good place to hide boogers",
  'Come up with the name for a new TV show with the word "Spanky" in it',
  "A fun trick to play on the Pope",
  "Where do you think the beef really is?",
  "Something it'd be fun to throw off the Eiffel Tower",
  "Write a newspaper headline that will really catch people's attention",
  'The worst job title that starts with "Assistant"',
  "The last person you'd consider inviting to your birthday party",
  "The grossest thing you'd put in your mouth for $18",
  "The name of a new perfume by Betty White",
  "The worst name for a robot",
  "The first names of each of your nipples",
  "The most embarrassing name for a dog",
  "The worst thing to discover in your burrito",
  "One thing never to do on a first date",
  "Ozzy Osbourne's Twitter password, probably",
  "Who let the dogs out?",
  "What do vegans taste like?",
  "An item NOT found in Taylor Swift's purse",
  "Name a new reggae band made up entirely of chickens",
  "Name a children's book by someone who hates children",
  "The name of your new plumbing company",
  "Make up a word that describes the sound of farting into a bowl of mac & cheese",
  "A new ice cream flavor that no one would ever order",
  "Name a new movie starring a talking goat who is president of the United States",
  "Something that would not work well as a dip for tortilla chips",
  "If God has a sense of humor, he welcomes people to heaven by saying ___",
  "The name of a clothing store for overweight leprechauns",
  "Something upsetting you could say to the cable guy as he installs your television service",
  "The worst thing that could jump out of a bachelor party cake",
  "Come up with a name for a new beer marketed toward babies",
  "A terrible theme for a high school prom",
  "Make up a name for a silent-film porno from the 1920s",
  "Something you should not whisper to your grandmother",
  "A terrible name for a 1930s gangster",
  "A fun thing to yell as a baby is being born",
  "The worst family secret that could come out over Thanksgiving dinner",
  "The name of a toilet paper specifically designed for the Queen of England",
  "Something you'd probably find a lot of in God's refrigerator",
  "The worst person to narrate the audiobook of \"Fifty Shades of Grey\"",
  "A lawn decoration sure to make the neighbors mad",
  "The worst thing to say when trying to adopt a pet",
  "A good name for an erotic bakery",
  "People wouldn't respect He-Man as much if, to gain his power, he held up his sword and shouted ___",
  "Fun thing to do if locked in the mall overnight",
  "The worst person to receive a sponge bath from",
  "Pants would be a whole lot better if they ___",
  "The most awesome Guinness World Record to break",
  "A little-known way to get gum out of your hair",
  "It's bad to be buried alive. It's worse to be buried alive with ___",
  "Something that would not work as well as skis",
  'A rejected title for "The Good, The Bad and the Ugly" was "The Good, the Bad and the ___"',
  "What to say to get out of jury duty",
  "What the Statue of Liberty is hiding beneath that robe",
  "There's only one time that murder is acceptable and that is when ___",
  "Take any well-known restaurant and slightly change its name to something inappropriate",
  "Little-known fact: The government allows peanut butter to contain up to 10% ___",
  "A good sign that your house is haunted",
  "A catchy name for a sperm bank",
  "A bad occupation for a robot to have",
  "A sequel to the painting Dogs Playing Poker",
  "The Tooth Fairy's other job",
  "Little-known fact: A secret area in the White House is the ___ room",
  "An invention by Thomas Edison that never caught on",
  "A bad place to skinny-dip",
  "What time is it?",
  "A birthday present you shouldn't get for your grandmother",
  "A short motto everyone should live by",
  "Invent a Christmas tradition sure to catch on",
  "A bad thing to yell during church",
  "The unsexiest thought you can have",
  "A good improvement to make to Mt. Rushmore",
  "The best way to start your day",
  "The worst name for a summer camp",
  "Something that's made worse by adding cheese",
  "Three things are certain in life: Death, Taxes, and ___",
  "A faster way to get home from the Land of Oz is to click your heels three times and say ___",
  "The first commandment in the new religion you started",
  "Come up with a name for a rock band made up entirely of baby ducks",
  "Something that is currently legal that should be banned",
  'A word that should never follow "Beef"',
  "The perfect song to hum on the toilet",
  "A bad thing to say to a cop as he writes you a speeding ticket",
  "Something you shouldn't buy off of Craigslist",
  "Take any U.S. president's name and turn it into something inappropriate",
  "We can all agree that ___",
  "The name you would give to a really mopey pig",
  "A great name to have on a fake I.D.",
  "What robots dream about",
  "What really happened to Amelia Earhart",
  "How far is too far?",
  "If at first you don't succeed...",
  'Finish this sentence: When I\'m rich, my mansion will have a room called The ___ Room',
  "Something you'd be surprised to see come out of a pimple you pop",
  "Today's music needs more ___",
  "A fun trick to play on your doctor",
  "A bad place for your rocket ship to crash would be The Planet of the ___",
  "A bad campaign slogan for a congressperson",
  "The coolest way to die",
  "Two people from history that should definitely have sex",
  "The name of an all-male version of Hooters",
  "A little-known nickname for New Orleans",
  "A unique way to escape from prison",
  "The title of a new YouTube cat video that's sure to go viral",
  "A gift nobody would want: The ___ of the Month Club",
  'A just-so-crazy-it\'s-brilliant business idea to pitch on "Shark Tank"',
  "A terrifying fortune cookie fortune",
  'It would be scary to read on a food package, "May contain trace elements of ___"',
  "What a dog sext message might say",
  "Something the devil is afraid of",
  "CBS should air a TV show about lawyers who are also ___",
  "A great thing to yell before jumping out of an airplane",
  "What you hope the Mars Rover finds",
  "A TMZ headline you really want to see",
  "Something that will get you thrown out of a Wendy's",
  "A rejected phrase for one of those Valentine heart candies",
  "Where missing socks go",
  "The first sign that you're old",
  "The name of a cocktail for hillbillies",
  "Graffiti you might find in a kindergarten",
  "The worst thing to wear to your court trial",
  "A rejected crayon color",
  "An angry review you'd give this game (Quiplash)",
  "Bad advice for new graduates",
  "The best way to tell if someone is dead",
  "A terrible talent to have for the Miss America Pageant",
  "Tomorrow's news headline: Scientists Are Shocked to Discover That ___",
  "The worst material with which to make a snowman",
  "A terrible sportscaster catchphrase for when somebody dunks a basketball",
  "The first thing a pig would say if it could talk",
  "A surprising job entry on Abraham Lincoln's resume",
  "The worst shape for an animal cracker",
  "A weird thing to find in your grandparents' bedside table",
  "The worst name for a big and tall store",
  "Something you'd yell to heckle the performing dolphins at Sea World",
  "A new name for kumquats",
  "The name of a shampoo for hippies",
  "The real secret to living to age 100",
  "What really happens if you tear off that mattress tag",
  "A bad first line for your presidential inauguration speech",
  "A fun thing to do with a bowl of pudding",
  "Another use for cooked spaghetti",
  "A weird physical way to greet someone",
  "The worst name for a tanning salon",
  'The worst word that can come before "fart"',
  "A bad substitute for a toothbrush",
  "A trick you shouldn't teach your dog",
  "A name for a really cheap hotel",
  "The second thing said on the moon",
  "Why so serious?",
  "A tourist attraction in Hell",
  "The worst name for a mountain",
  "A thought that keeps Santa Claus awake at night",
  "The best thing about being really dumb",
  "Come up with a name for a salad dressing by Lindsay Lohan",
  "What they call pooping in the Land of Oz",
  'A completely wrong way to spell "Jennifer Aniston"',
  "You know you're really drunk when...",
  "An animal Noah shouldn't have saved",
  "The biggest secret the government keeps",
  "Another use for gravy",
  "The worst name for a rap artist",
  "An angry internet comment on a pet store's website",
  "A rejected shape for Marshmallow Peeps",
  "Something that should never be homemade",
  "The worst name for a funeral home",
  "What Chewbacca has really been yelling all these years",
  "The worst car feature that ends with \"holder\"",
  "A Tweet from a caveman",
  "A great nickname for your armpit hair",
  "Pick any city name and make it sound dirty",
  "What you want your gravestone to read",
  "A slogan to get everyone excited about corn",
  "It never ends well when you mix ___ and ___",
  "The best reason to go to Australia",
  "The beauty pageant no one wants to see: Miss ___",
  "The perfect meal would be a ___ stuffed in a ___ stuffed in a ___",
  "What's black and white and red all over?",
  "A little-known fact about the Jolly Green Giant",
  "The worst thing to find growing on your neck",
  "USA! USA! America is still number one in...",
  "A good name for an elderly nudist colony",
  "You should never ___ and ___ at the same time",
  "What is a tree thinking all day?",
  "What you call a baby sasquatch",
  "A good name for a sex robot",
  "A bad reason to call 911",
  "Name the next big sexually transmitted disease",
  "The worst thing about Canada",
  "A strange thing to keep as a pet",
  "What kittens would say if they could talk",
  "A sign you probably shouldn't put up in your yard",
  "What dogs think when they see people naked",
  "The grossest thing you could find at the bottom of a swimming pool",
  "The worst name for an SUV",
  "A good use for toenail clippings",
  "The title of the most boring porno ever",
  "Something you shouldn't stuff with cheese",
  "Something Godzilla does when he's drunk",
  "Trash talk you would hear at a chess meet",
  "Tip: Never eat at a place called Kentucky Fried ___",
  "Something overheard at the Last Supper",
  "The name of a species of dinosaur you wouldn't want to meet",
  "The worst way to fly: ___ Airlines",
  "Little-known fact: Over the course of a lifetime, an average person accidentally eats ten ___",
  "A great pet name for a parasitic worm that lives in your ear",
  "A prank the Supreme Court Justices probably play on each other",
  "A crazy thing to find during a colonoscopy",
  "A word that should be in the dictionary but isn't",
  "Advice: Never stick your tongue into ___",
  "The perfect name for a second head that sprouts on your shoulder",
  "Something a weatherman might yell if he completely snapped during the weather forecast",
  "The worst advice a doctor could give",
  "Life hack! Lower your heating bills by...",
  "The worst thing that could crawl out of your toilet",
  "No one would guess this is where the treasure is buried",
  "How Garfield the cartoon cat will eventually die",
  "The worst pizza is ___-style pizza",
  "What to do when your parachute fails",
  "Sleepwalking can be a problem but it's not as bad as sleep___",
  "A good name for a dog country singer",
  "Little-known fact: the fourth Wise Man gave baby Jesus the worst gift of all: ___",
  "A theme for a desk calendar that wouldn't sell very well",
  "A good name for a restaurant that serves animals with the faces still on them",
  "This just in! A ___ has won the election and will become the new governor of Texas",
  "The worst Halloween costume for a young child",
  "A better name for the Washington Monument",
  "A terrible food truck would be one that goes around selling only ___",
  "The worst thing to overhear during your surgery",
  "A better name for dandruff",
  "The liquid that would make for the worst salad dressing",
  'Make up a word that means "to make up a word"',
  "Something you don't want to find in your Christmas stocking",
  "The most bitching thing you can airbrush on your van",
  "Something you'd love to smash with a wrecking ball",
  "What deer would use for bait if they hunted hunters",
  "The best name for an obese rapper",
  "If animals took over, an exhibit you'd see at the human zoo",
  "A magazine that should never have a nude centerfold",
  "Make up a word for the watery substance that comes out of a ketchup bottle when you first squeeze it",
  "A better name for the game Duck Duck Goose",
  "The worst children's board game would be ___ ___ Hippos",
  "The world's most boring video game",
  "The difference between Grade A beef and Grade B beef",

  // ── Quiplash 2 ─────────────────────────────────────────────────────────────
  "The gross thing nobody knows about the Easter Bunny",
  "It's one thing to take his gold, but the best way to make a leprechaun mad is to ___",
  "Another use for carrots",
  "What NASA doesn't tell us is that for years, they've observed ___ through a powerful telescope",
  "The #1 reason people flunk out of ninja school",
  "The title of the ultimate dream job",
  "The only thing you can remember from inside the womb",
  "A murder weapon that should be added to the next version of the game Clue",
  "The worst theme for a slot machine",
  "A really cool thing to be reincarnated as",
  "Spell out the sound a fish hitting a person in the face makes",
  "What are chicken nuggets really made out of?",
  "What are the three greatest words in the English language?",
  "What happens when you have your 10,000th poop?",
  "A terrible name for a morning talk show",
  'It would be weird if aliens arrived and the first thing they said was "Take us to your ___"',
  "Something unusual to see written on a bathroom stall",
  "The title of a sitcom starring an otter",
  "The worst sign-off line you could have on your email",
  "How the Monopoly guy really earned his wealth",
  "The hardest part of living forever",
  "In your opinion, scientists should be working around the clock to clone ___",
  'The three things that make up "old person smell"',
  "What did Adam and Eve REALLY do to get thrown out of the Garden of Eden?",
  "A fun thing to do in a grocery store when no one is looking",
  "You know your baby boy is growing up too fast when he starts to ___",
  "What the guy who used the first toilet said",
  "An odd thing to discover upon arriving in Heaven: Tuesday nights are ___ night",
  "What a drunk traffic reporter would say",
  "A terrible thing to announce on your first day in jail",
  "The title of a musical you're glad doesn't exist",
  "A creature you should never find on a carousel",
  "Why is each snowflake different?",
  "Finding money in an old pair of pants is great, but what's even better is discovering ___",
  "A group that no tour bus driver ever wants to have assigned to their bus",
  "The hardest part about dating in 1892",
  "The name of a really boring sex position is the Reverse ___",
  "The worst tattoo to have on your butt would consist of these three words",
  'A bad excuse for being late to your own wedding: "Sorry, I was ___"',
  "A weird thing for a baseball umpire to lean down and say to a catcher",
  "An event you would dominate at the Olympics: the 500-meter ___",
  "Tip: Take your large movie theater beverage cup home and use it for ___",
  "An ingredient you definitely shouldn't find in a bottle of water",
  "The worst donut in the world is filled with ___",
  "In your job, you don't need a bulletproof vest, you need a ___proof vest",
  'The sequel to the song "I Saw Mommy Kissing Santa Claus"',
  "The title of the shortest book ever written",
  "The scariest thing you could find in a cave",
  "Why do owls not kill us?",
  "What a lazy cowboy names his horse",
  "The best way to get out of a corn maze",
  "What a First Lady does all day",
  "The worst thing a lifeguard could announce to nearby swimmers",
  "The one thing they don't show you on the Pentagon tour is the secret ___ room",
  "The greatest part about having lots and lots of back hair",
  "The best way to escape the inside of a whale",
  "A food truck you might see in Texas: ___ On A Stick",
  "What happens if you eat too many hot dogs?",
  "The next big craze for yuppies: bottled ___",
  "Something you might overhear in a completely full clown car",
  'The worst possible misspelling of "Zach Galifianakis"',
  "A new baseball tradition you would like to see would be the seventh-inning ___",
  "Something very disturbing to pull out of your ear",
  "In the near future, scientists will discover that dinosaurs actually ___",
  "What are mannequins always thinking?",
  "Hands down, the worst roommate would be ___",
  "A car that would never sell is the Honda ___",
  "Never take a first date to a ___",
  "A funny line to say right before you're burned at the stake",
  "Everybody looks cool on a motorcycle except for ___",
  "What's that blue liquid in Magic 8 balls?",
  "The title of the book that's never checked out at the library",
  "A rejected song from the musical Oklahoma!",
  "You'll realize you shouldn't have picked up that hitchhiker when he says ___",
  "A good name for a Christian water park",
  "An item that never sells at a garage sale",
  "It would be awesome if you could grow ___ in a garden",
  "Something you don't want to see in a \"lost and found\" box",
  "The worst thing a history teacher could say",
  "The weirdest designated parking spot would be a parking spot specifically for ___",
  "A name for a dating site for people over 80",
  "A FAQ question on www.beets.com",
  "A terrible name for a dictator",
  "Indoor skydiving makes a lot more sense than indoor ___",
  "You can tell you're on a bad cruise when the captain announces \"If you look off the starboard side, you will see ___\"",
  "To be authentic, New York style pizza has to have lots and lots of ___",
  "The brand name of a really rough toilet paper",
  "You can tell your parents are glad to have you out of the house when they turn your room into a ___",
  "The quickest way to rid yourself of a tapeworm",
  "A hit country song for people who care about the environment",
  "What 80s TV alien ALF is probably up to right now",
  "Something that should never have a chocolate filling",
  "An inappropriate thing to write on somebody's cast",
  "What would you do for a Klondike bar?",
  'The technical medical term for "swamp ass"',
  "Something you wouldn't expect to hear from a Subway sandwich artist",
  "The biggest mistake you can make at an all-you-can-eat buffet",
  "Why you shouldn't party with Vikings",
  "A bad thing for a TV meteorologist to say during a tornado warning",
  "The name of a restaurant that only serves Grade D meat",
  "The worst thing to see out the window of your plane",
  "In the future, America will change its name to ___",
  "Why are sloths so slow?",
  'The three ingredients in a drink called "The Chicago"',
  "A street sign you would expect to see in Ireland",
  "A sign you got a bad nose job",
  "A procedure that not even the slimiest plastic surgeon will do",
  "The hardest class you can take at Clown College",
  "Edward Scissorhands would have been a much different movie if it were called Edward ___hands",
  "An unusual reason to duel somebody",
  "Somebody who would make a terrible soccer goalie",
  "A name for a lingerie store targeted to very conservative women",
  "A terrible name for a street",
  "A secret image hidden on the $1 bill",
  "A bad substitute for dental floss",
  "The scariest challenge that was never done on Fear Factor",
  "What cows are usually saying when they moo",
  "A bad line to have on your business card",
  "Never ___ after applying lotion",
  "A name that would always make a teacher laugh during roll call",
  "Something you should never think about while meditating",
  "A nutritional fact you'd find on a can of whoop ass",
  "If you really listen hard, you'll hear a seashell say this",
  "A good use for an abandoned mall",
  "The weirdest NASCAR sponsor you could see painted on a car",
  "A terrible place to dump grandma's ashes",
  "The worst thing to say during your Oscar award speech",
  "The worst gig for any truck driver would be delivering ___",
  'Should you catch on fire, remember, "Stop, Drop, Roll, and then ___"',
  "A really crappy nude calendar: The Men of ___",
  "A warning that should come with every IKEA futon",
  "How your spouse knows you're having an affair with a clown",
  "A bad thing to hear after yelling \"Hello!\" into a deep cave",
  "An awkward thing to say to the naked guy next to you on the bus",
  "A sign they should put up on the Florida state line",
  "How you would spend your first day as U.S. president",
  "A good name for a pet aardvark",
  "Why are printer ink cartridges so expensive?",
  "The title of a video game that would've been huge in the 1800s",
  "A weird thing to shout when you're mid-air during a cannonball",
  "A phrase nobody in the history of mankind has ever uttered",
  "A road sign that would cause you to turn around: \"Watch out for ___\"",
  'First-draft movie line: "Frankly, my dear, I ___"',
  "The worst song to lose your virginity to",
  "A terrible name for a hotel: The ___ Inn",
  "The worst topping to put on a cake",
  "WARNING: Never put ___ into a Crock-Pot",
  "Something that even a raccoon wouldn't eat",
  "Something that would be terrifying to notice in the background of a selfie",
  "The booth nobody visits at the job fair is for a business called ___",
  "An alternate name for meatloaf",
  "A good name for a band whose lead singer is a goat",
  "The name of an exhibit you'd be surprised to see at an art museum",
  "A terrible brand name for cat food",
  "The last thing you want to find in your cat's hairball",
  "What a caveman says right after sex",
  "New high school superlative: Most likely to ___",
  "The last sign we'll get before the apocalypse",
  "A good name for a roller derby team composed of nuns",
  "A terrible scent for a car freshener",
  "A three-word review of baths",
  "The next TV spin-off: Law and Order: Special ___ Unit",
  "The task that Satan's intern hates most",
  "The brand name of a patriotic line of diapers",
  "Something you don't want to hear from the skydiving instructor strapped to your back",
  "How you can spot a counterfeit Rolex",
  "The worst carnival attraction: The ___ Booth",
  "The worst time to tell someone you want a divorce is in the middle of ___",
  "The most important part of a hillbilly wedding",
  "What a rich jerk drinks champagne out of",
  "How does Swiss cheese get all those holes?",
  "A sign that your dog is an idiot",
  "A fun activity that only requires three fingers",
  "The first thing the ugly duckling did after turning into a beautiful swan",
  "What lobsters think as they are being boiled",
  "The wrong thing to say after farting in church",
  "Why haven't we been back to the moon?",
  "The worst crime in Middle-earth",
  "A really dumb name for a barbershop",
  "The one job robots will never take from humans",
  "To become a billionaire in mere days, simply ___",
  "How old-timey sailors passed the time on long voyages",
  "The last thing you want to find in a vacuum bag",
  "What are goats saying most of the time?",
  "The weirdest label you could have on a moving box",
  "The sound a black hole makes",
  "A rejected title in the Magic School Bus series: The Magic School Bus Goes to ___",
  "In the year 2085, ___ will be the American currency",
  "A great line to use to insert yourself into any conversation",
  "A dangerous thing for a drone to deliver to you",
  "The last thing you want to hear while in a tent",
  "A good reason to give a restaurant a zero star review",
  "Why are we put here on this Earth?",
  "Life hack! If you don't have a wine rack, simply use a ___",
  "Write a really dramatic line for a doctor to say in a TV medical drama",
  'The least impressive trophy: "1st place in ___"',
  "The hardest job to do while on roller skates",
  "The weirdest setting to find on a microwave would be a pre-programmed button for ___",
  "The title of the worst book to read on a toilet",
  'Proposed new Olive Garden slogan: "When you\'re here, you\'re ___"',
  "An idea for a really weird business: Rent-a-___",
  "An easy way to start a fire is to rub ___ together",
  "A good name for a Coldplay cover band",
  "A good way to get kicked out of a jazz band",
  "The best part about being an 1800s fur trapper",
  "A terrible drill sergeant would be constantly yelling ___",
  "The title of the shortest book ever written",
  "Remember, when buying a new home, always make sure the previous owner didn't ___",
  "An unusual store: ___ R' US",
  'A word that shouldn\'t come before "jerky"',
  "The worst TV program: ___ Dance Party",
  "Why is life so hard?",
  "Why the fish in your aquarium hate you",
  "A good use for 50 gallons of bacon grease",
  "A weird button in James Bond's car is simply labeled ___",
  "A new traffic law that really needs to happen",
  "Something you should never do without gloves on",
  "A warning that should come with spray-on cheese",
  "A great name for a real estate agent",
  "A sign your marriage may be falling apart",
  'The Teenage Mutant Ninja Turtles should update their catchphrase from "Cowabunga!" to "___!"',
  "The dumbest use of science would be to clone a ___",
  "What you will bequeath to your enemy upon your death",
  "A line in the Canadian national anthem, probably",
  "A clickbait headline about cows",
  "The worst thing an HR manager could wear",
  "The most pointless thing to strap a GoPro camera on",
  "A troubling thing to notice on your shirt tag: 2% ___",
  "The worst thing to say in a marriage proposal",
  "The last person you'd want to be on a lifeboat with",
  "Make up a name that probably no one in history has ever had",
  "The one thing that never sells at costume shops is a mask of ___",
  'The weirdest "talent" a beauty pageant contestant could showcase',
  "The last thing you want to hear from somebody sitting in front of you on a Megabus",
  "A strange thing to shout during a tickle fight",
  "An appropriate song to be playing at a sperm bank",
  "What ruined your hot air balloon ride?",
  "The devil's biggest complaint about Hell",
  "A bad excuse for missing your kid's graduation",
  "The name of a male strip show with really out-of-shape guys",
  "A disturbing thing to see your kid making out of clay",
  'The way to celebrate being honored as "Zoo Employee of the Month"',
  "Something you don't want to find in your grandpa's tool shed",
  "What a caveman has nightmares about",
  "The next way airlines will probably try to save money: ___",
  "The real reason the giant at the top of the beanstalk was trying to kill Jack",
  "What unicorn flatulence smells like",
  "Something you don't usually see on engaged couples' registry lists",
  "What's that smell?",
  "The hardest question a bridge troll could ask you",
  "Something in 98% of all cargo pants pockets",
  "The most inappropriate place to have a mechanical bull",
  "Bagels should change their name to ___",
  "The new menu item at Taco Bell in 2040 will be Chicken ___",
  "Terrible advice from a driver's ed instructor",
  "The one change churches could make that would probably get more people to attend",
  "A creative use for a corn cob",
  "The worst thing to paint on a new baby's nursery wall",
  "How do you seduce a bear?",
  "The weirdest event for which to camp out the night before",
  "The worst job to have at the White House",
  "Don't throw out those used chopsticks! They can be used to ___",
  "What a turtle looks for in a mate",
  "Breaking news! Scientists have just discovered nature's fiercest creature: the ___ shark",
  "The worst thing to wake up and find sitting on your chest",
  "A great use for a dirty diaper",
  "Conspiracy alert! Aliens are real and they're ___",
  "What the 13th month would be called",
  "The worst thing to have written on the butt area of your shorts",
  "The #1 cause of death for Care Bears",
  "What you've been searching for wasn't inside you this whole time. It was in ___",
  "The official name for the Pope's underwear",
  "A good name for a fictional town in Australia",
  "A great way to save electricity is to ___",
  "The worst excuse for ditching your date",
  "A weird thing for an astronaut to say on the moon",
  "The Eiffel Tower would be a lot cooler if it had ___",
  "The worst title for a rap song",
  'The worst thing to hear from your spouse: "I\'m leaving you for ___"',
  "You should always ___ before you get married",
  "Every airline flight should come with a free ___",
  "A weird way to keep your ears warm",
  "What a moron would say at a museum",
  "The name of a singles bar for pirates",
  "New rule: You should automatically be arrested if you ___",
  "The weirdest ingredient to put in trail mix",
  "A good line for breaking the tension at a fish funeral",
  "It's a bird, it's a plane, oh, wait, no. Nevermind, it's just ___",
  "The name of a clothing store for jockeys",
  "An inappropriate time to wear a tuxedo",
  "The title of a drama clearly gunning to win an Oscar",
  "A great name for a meteorologist",
  "The number one reported crime in Mister Rogers' neighborhood",
  "The worst vehicle to drag race in",
  "How to make golf more exciting",
  "The most common item in the Lost and Found box in Hell",
  "The weirdest menu item to choose for your last meal",
  "A secret Six Flags ride that only billionaires can go on",
  "The only thing we have to fear is fear itself. Oh, and also ___",
  "A weird plan for saving the manatees",
  "A strange thing for a ghost to whisper in your ear",
  "The most embarrassing thing that could happen at prom",
  "You get the weirdest image results when you search for ___",
  "A great pickup line to use in a retirement home",
  "The name of a really crappy robot",
  "A good sign that you accidentally married a duck",
  "A terrible name for a panini restaurant",
  "Some solid life advice: Never trust ___",
  "A campaign slogan guaranteed to get you elected president",
  "Something creepy to hear a kid say",
  "What Santa's elves do in the off-season",
  "A rejected name for nipples",
  "What the raccoons digging in your garbage say about you",
  "A bumper sticker a nudist would have",
  "A rejected Jelly Belly flavor",
  "The title of an album recorded by a singing goat",
  "A new slogan for the Greyhound bus company",
  "Women, never date a guy who ___",
  "The number one thing on Superman's bucket list",
  "More money, more ___",
  "After killing Hitler, the second thing you would do with a time machine",
  "The worst picture to see framed in your grandmother's house",
  "The title of a Goosebumps book that was never published",
  "Everybody Poops II: ___",
  "The scariest thing you can think of is ___ riding ___",
  "Alfred may know Batman's secret identity, but the biggest secret he keeps is ___",
  "Queen Elizabeth's wrestling name",
  "A good name for a mint for your butt",
  "A promise you shouldn't make to a sick child",
  "The worst thing to blurt out when watching a movie sex scene with your parents",
  "The worst catchphrase for a Star Trek captain",
  "The name of a cereal for serial killers",
  'The worst children\'s game: "Hungry, Hungry ___"',
  "A weird Tom Hanks/Meg Ryan movie: Sleepless in ___",
  "The title of an unreleased Air Bud movie",
  "The worst question to be asked at a lifeguard job interview",
  "What you shouldn't say as you're getting baptized",
  "A new, exciting rule for Monopoly: pass Go and collect ___",
  "What a really bad smuggler would say to a border guard",
  "The title of an erotic movie for elephants",
  "The name of a lingerie store for bears",
  "A sex position for ghosts",
  "A strange question to find on an IQ test",
  "The worst thing to see while wearing x-ray glasses",
  "Who's the boss?",
  "You know you've found your soulmate when you look them in the eye and they say ___",
  "The worst interrogation would have a good cop, a bad cop and a ___ cop",
  "Don't talk to me before I've had my coffee and don't touch me until I've had my ___",
  "Something you should never say when pulled over by a small town sheriff",
  "The employees at IKEA hate it when you ___",
  "The hardest part of having five secret families",
  "Something you shouldn't say to a mafia godfather",
  "A sign you may be a terrible babysitter",
  "A sign you may be in a cult",
  "Title of an HGTV show for bees",
  "A terrible thing to say while testing out a mattress",
  "A terrible name for a street drug",
  "The next big reality show: America's Got ___",
  "Why you're not allowed back at Jurassic Park",
  "The one thing that depresses Popeye",
  'Weird advice from your grandfather: "Don\'t take any wooden ___"',
  "The pep talk you'd get from a football coach who bet on the other team",
  "If you want to survive prison, walk up to the scariest prisoner and ___",
  "WARNING: The government allows school lunches to contain up to 4% ___",
  "There should be greeting cards specifically for this situation",
  'A rejected first-draft line from The Shining: "Here\'s ___!"',
  "How you know your RV is haunted",
  "What should be dumped on the losing coach at the end of a football game",
  "The worst thing to write in the tip section of a check",
  'A rejected church hymn: "Swing Low, Sweet ___"',
  "The worst place to fall asleep",
  "A question The Riddler asks on a first date",
  "A bad lawyer's opening statement to the jury",
  "Elvis' last words, probably",
  "A shocking thing to see digging through your garbage at night",
  "The perfect thing to say to get rid of door-to-door solicitors",
  "A new name for bananas",
  "A lame thing to say before your big drag race",
  "Elections would be a whole lot better if instead of debates, we made the candidates ___",
  "The name of a nightclub for people in their 40's",
  "The worst office has a view of ___",
  "Why Wolverine can't make a relationship work",
  "The one thing Spider-Man's spider-sense never warns him about",
  "The name of a bar with no bathrooms",
  "Wife Swap is a much better show than ___ Swap",
  "A terrible name for a yacht: The SS ___",
  "Something you don't want to hear from the guy driving your romantic horse-drawn carriage",
  "The name of a snobby hair salon for cats",
  "The worst thing to say as you enter a tough biker bar",
  'An interesting thing on Robocop\'s job performance review: "Needs to work on ___"',
  "The worst thing to say while being tortured",
  "A rejected name for a Crayola color",
  "A good name for a very cheap brand of whiskey",
  'A political slogan if a bear was running for President: "Make America ___ Again"',
  "Explain how babies are made in three words",
  "The perfect man is tall, dark and ___",
  "In the future, robots will do everything for us except ___",
  "A good sign your dog wears your clothes when you're not home",
  "The name of a horse you should never bet on",
  "A better name for belly buttons",
  "You know you have a shady landlord when ___",
  "It's sweet when grandma knits you a scarf. It's really weird when she knits you ___",
  "You know you're old when you're at a bar and the bartender asks you ___",
  "You know you're staying at a dirty hotel when they offer a free continental ___",
  "You know your company is going out of business when you show up to work and notice ___",
  "A great thing for a parent to say to scare their child's prom date",
  "A good joke to say while you're tied up in a basement",
  "A great way to get expelled from Hogwarts",
  "A family heirloom you probably shouldn't pass down to your children",
  "A sign your Roomba may be sentient",
  'A bad way to start your valedictorian speech would be "Ladies and gentlemen, I ___"',
  "Why the Tin Man isn't married",
  "Frankenstein's middle school nickname",
  "Harry Potter can do a really weird and obscure spell that allows him to ___",
  "When you cough up blood you should be concerned. When you cough up ___ you should be terrified",
  "The name of an animated movie that stars a surfing cow",
  "A weird catchphrase Jesus would say before performing a miracle",
  "What you say three times to summon Donald Trump",
  "The only things that can survive nuclear war are cockroaches and ___",
  "What NOT to say to a date while you're on a paddle boat",
  'An odd headline to see on the cover of Cosmo: "17 Tricks for ___"',
  "How did the ghosts in Pac-Man die?",
  "A new term for when you're drunk off mimosas",
  "A sign you never see: \"Honk if you're ___\"",
  "The sequel to Shakespeare in Love would be called Shakespeare in ___",
  "A cute thing a lawyer would say as he cuddles you",
  "Your awesome, new Witness Relocation Program name",
  "The worst part about having your human brain living in a robot body",
  'If a job interviewer asks "What\'s your biggest weakness?," always say ___',
  "What movie title best describes the state of your butt right now?",
  "You know it's love when you don't even hesitate when your lover asks you to ___",
  "Something you never want to hear a flight attendant say",
  "Yelling fire in a crowded movie theater is bad, but even worse is yelling ___",
  "A bouncy castle is cool, but a bouncy ___ is just sad",
  "If Michigan is shaped like a hand, Texas should be shaped like a ___",
  "You know you have a messed-up kid when they give you a crayon drawing of ___",
  "What a moody teen would say to hurt their step-dad, Bigfoot",
  "The worst place to put potato salad",
  "The saddest thing to say with a voice full of helium",
  "What Twinkies should be filled with",
  "You know you're going crazy when you hear the Rice Krispies say ___",
  "The worst thing to say in the backseat of a cop car",
  "A brand of pants for mermaids",
  "The name of a support group for men who can't grow beards",
  "If you want a really effective scarecrow, make sure it resembles ___",
  "The worst time to hear a camera go off",
  'The worst cocktail that ends in "-tini"',
  "A great way to make a dolphin mad is to ___",
  "A bad thing to hear the person cutting your hair say",
  'A great way to spice up baseball is the rule "Three Strikes and You\'re ___"',
  "How Papa Smurf plans to spend his retirement",
  "The reason the aliens stopped abducting you",
  'A terrible reply to the text "U up?"',
  "A mystery that Nancy Drew couldn't solve: The Case of the ___",
  "The worst toy you could find in a box of cereal",
  "The title of a cookbook written by a cowboy",
  "A terrible name for a toupee company",
  "A unique feature in a couch for billionaires",
  "The name of a fast food restaurant where the workers don't wear pants",
  "The best way to make a waiter at a snooty restaurant angry is to keep asking ___",
  'A rejected, less scary, title for the movie Jaws',
  "The title of a tell-all book by a former My Little Pony",
  "The name of a holiday you quickly make up to get out of work",
  "The worst thing to smell as you get into your car",
  'First-draft movie line: "Go ahead. Make my ___"',
  "A terrible thing to say to the bouncer checking your fake ID",
  "A bad way to make friends with your new next door neighbor",
  "The title of an action movie starring frogs",
  "The least popular scented candle smells like ___",
  "The title of a TV drama about a farmer who becomes a cop",
  "An odd thing to find in a cave painting",
  "The worst excuse Clark Kent has given Lois Lane so he could go change into Superman",
  "The worst thing you could try to donate to the Salvation Army",
  "Life hack! An ordinary melon baller can also be used for ___",
  "A good sign there's an invisible man living in your apartment",
  "The wrong thing to say to the kidnappers who have your husband",
  "The most disappointing thing to win on a game show: a lifetime supply of ___",
  "When confronted by a mountain lion, stay calm, stand as tall as possible, and ___",
  'A wise old saying your grandma taught you: "Look before you ___"',
  "A rejected superhero vehicle: the ___mobile",
  "You know it's time to lose weight when your gut blocks your view of ___",
  'A weird surgery that starts with "Laser"',
  "What you might hear Big Bird say on his deathbed",
  "The worst way to die: death by a thousand ___",
  "A bad name for a proctologist: Dr. ___",
  "Snow White's biggest complaint about living with the Seven Dwarfs",
  "The worst thing to get stuck in your hair",
  "A good taunt to yell at the zoo elephants",
  "The most popular ride at a religious theme park",
  "The worst thing to say during your Supreme Court Justice confirmation hearing",
  "The most inappropriate song to be air drumming to",
  "A good replacement for Sea World's whale shows would be ___",
  "The worst bachelor party would involve ___",
  "What the world's most obnoxiously trendy brunch restaurant would be called",
  "A strange thing to keep as a pet",
  "A job that doesn't exist now, but that somebody probably had in olden times",
  "A good name for a sex robot",
  "The worst reason to call 911",
  "What the hare did with his life after losing to the tortoise",
  "The best part about being Donald Trump",
  "A movie that needed more nudity",
  "The worst person who could sing the James Bond theme",
  "A new children's classic: The Velveteen ___",
  "The title of a Goosebumps book that was never published",
  "What the S stands for in Ulysses S. Grant",
  "A good name for a mint for your butt",
  "A rejected Jelly Belly flavor",
  "The worst catchphrase for a Star Trek captain",
] as const;